-- Товары магазина. Источник данных — вместо dummyjson.com.
-- dummyjson_id уникален, чтобы повторный запуск заливки не создавал дубли.
create table if not exists public.products (
    id bigint generated by default as identity primary key,
    dummyjson_id bigint unique,
    title text not null,
    description text not null default '',
    price numeric(10, 2) not null default 0,
    stock integer not null default 0,
    created_at timestamptz not null default now()
);

alter table public.products enable row level security;

-- Публичное чтение: API-запросы с anon-ключом могут только SELECT.
-- Edge Function ходит с service_role и обходит RLS.
create policy "public read products"
    on public.products
    for select
    to anon, authenticated
    using (true);
