-- Журнал диалогов: каждая текстовая реплика — входящая от человека ('in')
-- и исходящий ответ бота ('out'). История для аналитики и отладки.
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    username text,
    chat_id bigint not null,
    text text not null,
    direction text not null check (direction in ('in', 'out')),
    created_at timestamptz not null default now()
);

-- Журнал читают «по клиенту, от свежих к старым» — индекс под эти запросы
create index if not exists messages_user_created_idx
    on public.messages (user_id, created_at desc);

alter table public.messages enable row level security;

-- Намеренно БЕЗ политик (в отличие от products): переписка — приватная.
-- С anon-ключом таблица недоступна на чтение; Edge Function пишет через
-- service_role (обходит RLS), владелец смотрит в Table Editor / SQL Editor.
